require('dotenv').config();
const express=require('express'),crypto=require('crypto'),path=require('path');
const {Pool}=require('pg');
const app=express(), pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:undefined});
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type,x-admin-password');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.use(express.json({limit:'3mb'}));app.use(express.static('public'));
const admin=(req,res,next)=>{if(req.headers['x-admin-password']!==(process.env.ADMIN_PASSWORD||''))return res.status(401).json({error:'Unauthorized'});next()};
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,price_cents INTEGER NOT NULL,category TEXT NOT NULL,description TEXT DEFAULT '',stock INTEGER NOT NULL DEFAULT 0,badge TEXT DEFAULT '',image TEXT DEFAULT '',active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,created_at TIMESTAMPTZ DEFAULT NOW(),name TEXT NOT NULL,email TEXT NOT NULL,fulfillment TEXT NOT NULL,total_cents INTEGER NOT NULL,status TEXT NOT NULL,payment_id TEXT,items JSONB NOT NULL); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); ALTER TABLE orders ADD COLUMN IF NOT EXISTS phone TEXT; ALTER TABLE orders ADD COLUMN IF NOT EXISTS dropoff_location TEXT;`)}
const productOut=r=>({id:r.id,name:r.name,price:r.price_cents/100,category:r.category,description:r.description,stock:r.stock,badge:r.badge,image:r.image,active:r.active});
app.get('/api/products',async(req,res)=>{try{let {rows}=await pool.query('SELECT * FROM products WHERE active=TRUE ORDER BY created_at DESC');res.json(rows.map(productOut))}catch(e){res.status(500).json({error:'Database unavailable'})}});
app.get('/api/config',async(req,res)=>{let r=await pool.query("SELECT value FROM settings WHERE key='dropoff_fee_cents'");let dropoffFee=r.rows[0]?Number(r.rows[0].value)/100:0;res.json({appId:process.env.SQUARE_APP_ID||'',locationId:process.env.SQUARE_LOCATION_ID||'',environment:process.env.SQUARE_ENV||'sandbox',dropoffFee})});
app.get('/api/admin/summary',admin,async(req,res)=>{let rr=await pool.query("SELECT value FROM settings WHERE key='sales_reset_at'");let resetAt=rr.rows[0]?.value||'1970-01-01T00:00:00.000Z';let p=await pool.query('SELECT COUNT(*)::int AS products FROM products WHERE active=TRUE');let o=await pool.query('SELECT COUNT(*)::int AS orders FROM orders');let rev=await pool.query("SELECT COALESCE(SUM(total_cents),0)::bigint AS cents FROM orders WHERE status IN ('PAID','COMPLETED') AND created_at >= $1",[resetAt]);res.json({products:p.rows[0].products,orders:o.rows[0].orders,paidSales:Number(rev.rows[0].cents)/100,salesResetAt:resetAt})});
app.get('/api/admin/products',admin,async(req,res)=>{let {rows}=await pool.query('SELECT * FROM products ORDER BY created_at DESC');res.json(rows.map(productOut))});
app.post('/api/admin/products',admin,async(req,res)=>{try{let p=req.body,id=crypto.randomUUID();let q=await pool.query('INSERT INTO products(id,name,price_cents,category,description,stock,badge,image) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[id,p.name,Math.round(Number(p.price)*100),p.category,p.description||'',Math.max(0,Number(p.stock)||0),p.badge||'',p.image||'']);res.json(productOut(q.rows[0]))}catch(e){res.status(400).json({error:'Could not save product'})}});
app.put('/api/admin/products/:id',admin,async(req,res)=>{try{let p=req.body;let q=await pool.query('UPDATE products SET name=$2,price_cents=$3,category=$4,description=$5,stock=$6,badge=$7,image=$8 WHERE id=$1 RETURNING *',[req.params.id,p.name,Math.round(Number(p.price)*100),p.category,p.description||'',Math.max(0,Number(p.stock)||0),p.badge||'',p.image||'']);res.json(productOut(q.rows[0]))}catch(e){res.status(400).json({error:'Could not update product'})}});
app.delete('/api/admin/products/:id',admin,async(req,res)=>{await pool.query('DELETE FROM products WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.get('/api/admin/orders',admin,async(req,res)=>{let {rows}=await pool.query('SELECT * FROM orders ORDER BY created_at DESC');res.json(rows.map(o=>({...o,total:o.total_cents/100,createdAt:o.created_at})))});
app.put('/api/admin/orders/:id',admin,async(req,res)=>{let allowed=['PAID','PREPARING','READY','SHIPPED','COMPLETED','DEMO'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});await pool.query('UPDATE orders SET status=$2 WHERE id=$1',[req.params.id,req.body.status]);res.json({ok:true})});
app.post('/api/checkout',async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');let {sourceId,name,email,phone,fulfillment,dropoffLocation,items}=req.body;if(!name||!email||!phone||!Array.isArray(items)||!items.length)throw Error('Missing checkout information');if(!['Local pickup','Local drop-off'].includes(fulfillment))throw Error('Choose a valid fulfillment option');if(fulfillment==='Local drop-off'&&!dropoffLocation)throw Error('Drop-off location is required');let ids=items.map(i=>i.id),{rows}=await client.query('SELECT * FROM products WHERE id=ANY($1::text[]) FOR UPDATE',[ids]);let map=new Map(rows.map(r=>[r.id,r])),normalized=[],cents=0;for(let i of items){let p=map.get(i.id),qty=Math.max(1,Number(i.qty)||1);if(!p||!p.active)throw Error('A product is no longer available');if(qty>p.stock)throw Error(`${p.name} does not have enough stock`);normalized.push({id:p.id,name:p.name,price:p.price_cents/100,qty});cents+=p.price_cents*qty}if(fulfillment==='Local drop-off'){let fr=await client.query("SELECT value FROM settings WHERE key='dropoff_fee_cents'");let fee=fr.rows[0]?Number(fr.rows[0].value):0;if(!fee)throw Error('Local drop-off fee is not configured');cents+=fee}
let paymentId=null,demo=(process.env.SQUARE_ENV||'sandbox')!=='production'&&!process.env.SQUARE_ACCESS_TOKEN;
if(!demo){if(!process.env.SQUARE_ACCESS_TOKEN)throw Error('Square is not configured');let host=(process.env.SQUARE_ENV==='production')?'https://connect.squareup.com':'https://connect.squareupsandbox.com';let pr=await fetch(host+'/v2/payments',{method:'POST',headers:{Authorization:`Bearer ${process.env.SQUARE_ACCESS_TOKEN}`,'Content-Type':'application/json','Square-Version':'2026-09-16'},body:JSON.stringify({source_id:sourceId,idempotency_key:crypto.randomUUID(),amount_money:{amount:cents,currency:'USD'},autocomplete:true,location_id:process.env.SQUARE_LOCATION_ID,note:`Mimi's Squishies order for ${name}`})});let pd=await pr.json();if(!pr.ok)throw Error(pd.errors?.[0]?.detail||'Square payment failed');paymentId=pd.payment.id}
let id='MS-'+Date.now().toString().slice(-8);for(let i of normalized)await client.query('UPDATE products SET stock=stock-$2 WHERE id=$1',[i.id,i.qty]);await client.query('INSERT INTO orders(id,name,email,phone,fulfillment,dropoff_location,total_cents,status,payment_id,items) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,name,email,phone,fulfillment,dropoffLocation||null,cents,demo?'DEMO':'PAID',paymentId,JSON.stringify(normalized)]);await client.query('COMMIT');res.json({ok:true,demo,order:{id,total:cents/100,status:demo?'DEMO':'PAID'}})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message||'Checkout failed'})}finally{client.release()}});
app.get('/api/admin/settings',admin,async(req,res)=>{let r=await pool.query("SELECT value FROM settings WHERE key='dropoff_fee_cents'");res.json({dropoffFee:r.rows[0]?Number(r.rows[0].value)/100:0})});
app.put('/api/admin/settings',admin,async(req,res)=>{let fee=Number(req.body.dropoffFee);if(!Number.isFinite(fee)||fee<0)return res.status(400).json({error:'Invalid fee'});let cents=Math.round(fee*100);await pool.query("INSERT INTO settings(key,value) VALUES('dropoff_fee_cents',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[String(cents)]);res.json({ok:true,dropoffFee:cents/100})});

app.post('/api/admin/reset-sales',admin,async(req,res)=>{let now=new Date().toISOString();await pool.query("INSERT INTO settings(key,value) VALUES('sales_reset_at',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[now]);res.json({ok:true,salesResetAt:now})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(process.env.PORT||3000,()=>console.log('Mimi shop ready'))).catch(e=>{console.error('DB init failed',e);process.exit(1)});